dbDetails:
  database: default_name
  host: localhost
  backupDir: /tmp/dbBackUp

superUser:
  user: postgres
  password: postgres

mainUser:
  user: main
  password: password

blindReviewers:
  reviewer1:
    name: 'first last'
    to_score_dir: '/tmp/reviewer1/toScore_R1/'
    scored_dir: '/tmp/reviewer1/scored_R1/'
